version: '3.8'

services:

  kurkkumopo-front-service:
    image: kurkkumopo_front_image
    ports:
      - 3000:3000
    build: ./ml-kurkkumopo-frontend
    container_name: kurkkumopo_front_container

  kurkkumopo-back-service:
    image: kurkkumopo_back_image
    ports:
      - 5000:5000
    build: ./ml-kurkkumopo-backend
    volumes:
      - ./model:/src/model
    container_name: kurkkumopo_back_container

  kurkkumopo-training-service:
    image: kurkkumopo_training_image
    build: ./ml-kurkkumopo-training
    volumes:
      - ./model:/src/model
      - ./imgs:/src/imgs
    container_name: kurkkumopo_training_container